### ISSUE TITLE
Confusing color scale in quantile calibration multiplot

### ISSUE THREAD

**Issue by ghost** [Ouranosinc/scen_workflow_afr#6]
* xclim version: 0.25.0
* Python version: 3.7.6
* Operating System: LinuxMint 20.1

### Description
Adjust the color scale in the quantile calibration multiplot to ensure that white in the plot displaying the transfer function (upper left box) corresponds to zero.

### What needs to be done
Play with the lower and upper limits defining the colorbar so that `abs(min_val) == max_val`. This will also let the color intensity be proportional to the bias adjustment (relative to zero). This is the method selected do display anomaly maps (see `plot.plot_heat`).

### What I Received
This section is not required.

**Comment by Zeitsperre** [comment]
Closing issue to archive project.
