### ISSUE TITLE
Produce boxplots for each variable and climate index

### ISSUE THREAD

**Issue by ghost** [Ouranosinc/scen_workflow_afr#7]
* xclim version: 0.25.0
* Python version: 3.7.6
* Operating System: LinuxMint 20.1

### Description
It could be useful (for interpretation) to produce boxplots (and equivalent .csv files if the option is enabled) for each variable and climate index.

### What needs to be done
Develop methods similar to `scenarios.gen_plot_freq` and `plot.plot_boxplot` (or modify existing ones). The difference would be that we have simulations on the x-axis (instead of months). I built an Excel prototype, but never integrated the diagrams into a report. The information was simply overwhelming for a regular stakeholder, but it could be useful internally when exploring the data.

### What I Received
This section is not required.

**Comment by Zeitsperre** [comment]
Closing issue to archive project.
