### ISSUE TITLE
Standardizing attributes and dimensions in NetCDF files and loaded objects

### ISSUE THREAD

**Issue by ghost** [Ouranosinc/scen_workflow_afr#8]
* xclim version: 0.25.0
* Python version: 3.7.6
* Operating System: LinuxMint 20.1

### Description
The code needs to be adjusted to ensure that the structure of the NetCDF files produced by the workflow, along with the structure of the objects loaded in memory during a run, is consistent throughout, and is CF- and COARDS-compliant.

### What needs to be done
The presence of lon/lat, rlon/rlat, longitude/latitude in instances of `xarray.DataArray` and `xarray.Dataset` makes the code more complex because dimensions often need to be renamed and/or reordered. Some functions (ex: clisops.core.subset.subset_shape) will only work if a specific set of coordinate names is present in the instance passed to the function. This is one obvious example of a potential improvement, but the objective would be to be as consistent as possible.

### What I Received
This section is not required.

**Comment by Zeitsperre** [comment]
Closing issue to archive project.
